# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lat', models.CharField(max_length=10)),
                ('log', models.CharField(max_length=10)),
                ('avatar', models.FileField(upload_to='/avatar')),
            ],
        ),
    ]
