# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='avatar',
            field=models.ImageField(upload_to='/avatar'),
        ),
    ]
