# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160804_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
